### ems_1
@agent_server_uri = https://ces-skbroadband-agent-stage.com

POST {{agent_server_uri}}/api/v1/ems/job/create
content-type: application/json

{
  "ems_user_id": "bmt-test",
  "series_id": "CS10006",
  "episode_id": "CE10006",
  "content_name": "TC-CES-006_캐리와-장난감-친구들-숨바꼭질-시즌10-제-4화_1min",
  "origin_file_name": "TC-CES-006_캐리와-장난감-친구들-숨바꼭질-시즌10-제-4화_1min.mxf",
  "request_time": "20220602192000",
  "input_file_duration_time": "00:00:10",
  "genre": "NONE",
  "resolution": "FHD",
  "input_file_key": "bmt-test/TC-CES-006_캐리와-장난감-친구들-숨바꼭질-시즌10-제-4화_1min.mxf",
  "encoding_profiles": {
    "CE10006": [
      {
        "video_profile": "TV-HD-H264-TS",
        "audio_profile": "TV-MC-1TK-AAC-2CH"
      }
    ]
  }
}